export enum ErrorName {
    CREATE_LISTING_ERROR = "CREATE LISTING ERROR",
    FETCH_LISTING_DETAILS_ERROR = "FETCH LISTING DETAILS ERROR",
    UPLOADING_IMAGE_ERROR = "UPLOADING IMAGE ERROR",
    FETCH_LISTINGS_ERROR = "FETCH LISTINGS ERROR",
}
